name = "motion-cloudflare"
main = "index.js"
compatibility_date = "2026-03-01"

[env.production.vars]
# 環境変数があればここに書く

[[d1_databases]]
binding = "DB"
database_name = "motion-db"
database_id = "ここにD1データベースのIDを貼り付けます"
